- name: Kalliope web_scraper neuron install
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: xextract
        version: 0.1.4

